### ISSUE TITLE
Cannot Install Ruby

### ISSUE THREAD

**Issue by patriciapadilhacoleman** [learn-co-curriculum/macos-env-ruby#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
Error running '__rvm_make -j4',
please read /Users/patriciacoleman/.rvm/log/1641252921_ruby-3.1.0/make.log

```

## What OS Are You Using?

- [ X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by ihollander** [comment]
Hi @patriciapadilhacoleman - thanks for flagging this issue. It looks like you're using an outdated version of the environment setup instructions. Here's the latest version: https://github.com/learn-co-curriculum/phase-0-macos-env-ruby

If you're running into issues when setting up your environment, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Hope you are able to get this resolved!
